#!/usr/bin/env python3

import sys
import csv
import html

def _escape(s):
    return s.replace("&", "&amp;")

def _xmlify(matches):
    items = ""
    for match in matches:
        desc, entity = match

        # encode the first of potentially multiple aliases
        title = html.unescape(entity.split(" ")[0])
        subtitle = _escape(f"{desc} ({entity})")

        items += "<item>"
        items += f"<title>{title}</title><subtitle>{subtitle}</subtitle><arg>{title}</arg>"
        items += "</item>"
    return f'<?xml version="1.0" encoding="utf-8"?><items>{items}</items>'

def _matches(queries, desc, entity):
    for query in queries:
        if query not in entity and query not in desc:
            return False
    return True

args = " ".join(sys.argv[1:])
queries = list(map(lambda s: s.strip().lower(), args.split(" ")))

# list of tuples: (desc, entity)
matches = []

with open("entities.db", mode="r", encoding="utf8") as f:
    matches = [(desc, entity) for (desc, entity) in csv.reader(f) if _matches(queries, desc, entity)]

if len(matches) > 0:
    print(_xmlify(matches))
else:
    sys.exit(1)

