#!/usr/bin/env python3

import sys
import csv
import html

def _xmlify(matches):
    items = ""
    for match in matches:
        items += "<item>"
        items += "<title>{}</title><subtitle>{}</subtitle><arg>{}</arg>".format(*match)
        items += "</item>"
    return f'<?xml version="1.0" encoding="utf-8"?><items>{items}</items>'

def _matches(queries, desc, entity):
    for query in queries:
        if query not in entity and query not in desc:
            return False
    return True

args = " ".join(sys.argv[1:])
queries = list(map(lambda s: s.strip().lower(), args.split(" ")))

# list of tuples: (title, subtitle, arg)
matches = []

with open("entities.db", mode="r", encoding="utf8") as f:
    for row in csv.reader(f):
        desc, entity = row

        if _matches(queries, desc, entity):
            # encode the first of potentially multiple aliases
            htm = html.unescape(entity.split(" ")[0])
            codes = entity.replace("&", "&amp;")
            matches.append((htm, f"{desc} ({codes})", htm))

if len(matches) > 0:
    print(_xmlify(matches))
else:
    sys.exit(1)

